# Generated by Django 5.0.6 on 2024-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_web_shop_app', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('size_type', models.CharField(choices=[('NUM', 'Numerical'), ('CAT', 'Categorical')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='football_web_shop_app.size'),
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
