# Generated by Django 5.0.6 on 2024-06-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_web_shop_app', '0007_category_parent_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_staus',
            new_name='paid_status',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='football_web_shop_app.size'),
        ),
    ]
