# Generated by Django 5.0.6 on 2024-06-10 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_web_shop_app', '0009_alter_product_image_alter_productimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_image', to='football_web_shop_app.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='football_web_shop_app.product'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_type',
            field=models.CharField(choices=[('NUM', 'Numerical'), ('CAT', 'Categorical')], max_length=10),
        ),
    ]
