# Generated by Django 5.0.6 on 2024-06-17 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_web_shop_app', '0016_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='football_web_shop_app.brand'),
        ),
    ]
