# Generated by Django 5.0.6 on 2024-06-17 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_web_shop_app', '0017_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='football_web_shop_app.size'),
            preserve_default=False,
        ),
    ]
