# Generated by Django 5.0.6 on 2024-06-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_web_shop_app', '0022_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock_quantity',
        ),
    ]
