# Generated by Django 5.0.6 on 2024-06-28 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_web_shop_app', '0023_rename_quantity_product_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_web_shop_app.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_web_shop_app.size')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
